# Generated by Django 5.1.2 on 2024-11-08 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DS_Lop',
            fields=[
                ('Ma_hv', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=100)),
                ('Don_vi', models.CharField(max_length=100)),
                ('Ngay_sinh', models.DateField()),
                ('Que_quan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DS_DangKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=100)),
                ('Don_vi', models.CharField(max_length=100)),
                ('Sdt_nguoi_than', models.CharField(max_length=15)),
                ('Ly_do', models.TextField()),
                ('Dia_diem', models.CharField(max_length=100)),
                ('Ngay_dang_ky', models.DateField()),
                ('Thoigian_ra', models.TimeField()),
                ('Thoigian_vao', models.TimeField()),
                ('Phe_duyet', models.BooleanField(default=False)),
                ('Ma_hv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.ds_lop')),
            ],
        ),
        migrations.CreateModel(
            name='DS_NhatKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=100)),
                ('Noi_dung', models.CharField(max_length=256)),
                ('Ngay_dang_ky', models.DateField()),
                ('is_vipham', models.BooleanField(default=False)),
                ('is_thanhtich', models.BooleanField(default=False)),
                ('Diem', models.IntegerField()),
                ('Ma_hv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.ds_lop')),
            ],
        ),
    ]
